!
!       3/ /00 copied by rjg from somewhere on hp-ux because version on
!              vms is not up to date
!       4/4/00 revised by rjg for f90
!       4/5/00 revised by rjg for f90 to use HP_ALIAS
!
!       mdslib.inc

!$HP$ ALIAS DESCR         = "descr"
!$HP$ ALIAS MdsValue      = "MdsValue"
!$HP$ ALIAS MdsConnect    = "MdsConnect"
!$HP$ ALIAS MdsOpen       = "MdsOpen"
!$HP$ ALIAS MdsPut        = "MdsPut"
!$HP$ ALIAS MdsClose      = "MdsClose"
!$HP$ ALIAS MdsSetDefault = "MdsSetDefault"
!$HP$ ALIAS MdsDisconnect = "MdsDisconnect"
!
