#
# stage0 is a convenience.  We have it set to not run for every MR, but the MR
# will show a button that you can click to start an MR. 
#
# stage1 is done at hip.txcorp.com and is not debug
#
# Goal is to eventually have stages for testing:
#    1. More complete build (with NetCDF, MPI, and HDF5)
#    2. Testing more compilers (Intel, PGI, Cray)
#    3. Higher resolution (make separate stage to save time)
#    4. At NERSC
#    5. At GA with MDS+

stages:
  - stage0
  - stage1

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: -ffdxq
  TIMEOUT: 450


# The most basic template that most tests will expand upon
#

.test-basic:
  interruptible: true
  only:
    refs:
#     Set with CI/CD Shedules - New Schedule
      - schedules
      - api
#     Set with CI/CD Pipelines - Run Pipeline
      - web
      - merge_requests
  dependencies: []

.test:
  extends: .test-basic
  except:
    variables:
      - $EFIT_CI_SCHEDULED =~ /yes/

pause-for-approval:
  extends: .test
  stage: .pre
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_EVENT_TYPE == "merged_result"
      - $CI_MERGE_REQUEST_EVENT_TYPE == "detached"
  script:
    - echo "pause-for-approval has no script to run"
  variables:
    GIT_STRATEGY: none
  when: manual
  allow_failure: false

clang-docker:
  extends: .test
  stage: stage0
  image: registry.gitlab.com/efit-ai/efit/clang
  # Note that currently I'm not actually running make test
  script:
    - mkdir build && cd build # Build out of place
    - ../docker/config_docker_clang.sh
    - make -j4

linux-clang:
  extends: .test
  stage: stage1
  tags:
    - name:hip.txcorp_efitai
  script:
    - mkdir build && cd build # Build out of place
    - ../share/config_examples/config_ci_hip.sh
    - make -j4
    - make test
  variables:
    PATH: /scratch/soft/bin:/scratch/soft/mpich/bin:/opt/rh/devtoolset-7/root/usr/bin:/usr/bin:/bin
