# Build command:
#   $ docker build -t efit/clang -f Dockerfile.clang  .
FROM debian:stable-slim


RUN apt-get update && apt-get install -y \
        curl \
        environment-modules \
        git \
        python3 \
        python3-pip \
        unzip \
        texlive-bibtex-extra \
        doxygen \
        vim \
        wget \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PREFIX=/scratch

RUN python3 -m pip install --no-cache-dir -U pip

# For building documentation
RUN python3 -m pip install --no-cache-dir Sphinx
RUN python3 -m pip install --no-cache-dir pydata-sphinx-theme
RUN python3 -m pip install --no-cache-dir sphinxcontrib-bibtex
RUN python3 -m pip install --no-cache-dir breathe

# For linting
RUN python3 -m pip install --no-cache-dir lxml
RUN python3 -m pip install --no-cache-dir mypy

ENV HOME=/root
