# Build command:
#   $ docker build -t registry.gitlab.com/efit-ai/efit/pytorch -f Dockerfile.pytorch .

FROM condaforge/mambaforge:4.9.2-5 as conda
RUN $PWD/bin/conda -V && \
    $PWD/bin/conda install pytorch torchvision torchaudio -c pytorch

FROM registry.gitlab.com/efit-ai/efit/pybase:latest
RUN python3 -m pip install --no-cache-dir torch

ENV HOME=/root
